### ISSUE TITLE
Progress so far?

### ISSUE THREAD

**Issue by ririinsta** [ChefKissInc/qemu-apple-silicon#9]
First off, love your work with nootedred. Second, while looking into the original repo for this I noticed you guys forked it and have made 8000~ commits more than the original. What does the progress on it look like so far? Any progress on emulating SEP or running springboard?

**Comment by VisualEhrmanntraut** [comment]
Hi there, see the dev branch for progress. SpringBoard requires SEP to be functional in order to work. We are currently working on SEP support, SEP ROM's running to some degree. Locally my colleague @chris-pcguy has made more progress getting SEP/OS to be booted, but SEP/OS is still not functional (does not respond to pings) due to currently unknown reasons. I'm working on booting iOS on the s8000 SoC, since running the SEP is easier there (32-bit and no boot monitor).

**Comment by ririinsta** [comment]
I see. Would it be easier to get iOS running on a SoC that doesn't have a SEP? Like the A6 for example. I don't know a lot about the inner workings of either SoCs so I am not sure if that is unreasonable or not. I know that chips A7 and above don't have a SEP so it made me wonder if getting those running would be easier.

**Comment by VisualEhrmanntraut** [comment]
Secure Enclave was added in A7, I assume you meant "I know that chips before the A7 ...". Yes it would be easier, but what's the point?

**Comment by ririinsta** [comment]
Yes that is what I meant, sorry had a long day. I just thought that it would be cool to get springboard loading in some capacity even if it is a older version.

**Comment by VisualEhrmanntraut** [comment]
If you just want to get SpringBoard on some random iDevice, you can look at this fork: https://github.com/devos50/qemu-ios that has it up on iPod Touch 1G and 2G (different branches)

**Comment by ririinsta** [comment]
Interesting. Thank you for answering my questions about the project. I wish you the best of luck. And once again thank you for NootedRed and NootRX (going to go try it out after I am done with this comment).

**Comment by LetsUnlockiPhone** [comment]
Any chance of SEP will be added to this fork? Thanks

**Comment by VisualEhrmanntraut** [comment]
@LetsUnlockiPhone That’s what we are working on in the dev branch.
